<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="143" started-at="2019-04-23T13:59:07Z" finished-at="2019-04-23T13:59:08Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="143" started-at="2019-04-23T13:59:07Z" finished-at="2019-04-23T13:59:08Z">
      <class name="tests.FirstTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.FirstTests@51081592]" name="setUp" is-config="true" duration-ms="67" started-at="2019-04-23T13:59:07Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="classIsNullTest()[pri:0, instance:tests.FirstTests@51081592]" name="classIsNullTest" duration-ms="8" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Se espera que el primero sea mayor al segundo expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Se espera que el primero sea mayor al segundo expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at tests.FirstTests.classIsNullTest(FirstTests.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classIsNullTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.FirstTests@51081592]" name="setUp" is-config="true" duration-ms="1" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="miCuartoTest()[pri:0, instance:tests.FirstTests@51081592]" name="miCuartoTest" duration-ms="2" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- miCuartoTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.FirstTests@51081592]" name="setUp" is-config="true" duration-ms="2" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="miPrimerTest()[pri:0, instance:tests.FirstTests@51081592]" name="miPrimerTest" duration-ms="4" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Se esperan los dos iguales expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Se esperan los dos iguales expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at tests.FirstTests.miPrimerTest(FirstTests.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- miPrimerTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.FirstTests@51081592]" name="setUp" is-config="true" duration-ms="3" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="miSegundoTest()[pri:0, instance:tests.FirstTests@51081592]" name="miSegundoTest" duration-ms="4" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- miSegundoTest -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.FirstTests@51081592]" name="setUp" is-config="true" duration-ms="1" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="miTercerTest()[pri:0, instance:tests.FirstTests@51081592]" name="miTercerTest" duration-ms="2" started-at="2019-04-23T13:59:08Z" finished-at="2019-04-23T13:59:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- miTercerTest -->
      </class> <!-- tests.FirstTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
